---
- name: Configure Podman host
  hosts: docker_hosts
  become: true
  gather_facts: false

  tasks:
    - name: Include dockge service task
      ansible.builtin.include_tasks:
        file: ad_hoc_tasks/dockge_service.yml
