---
- name: Set system timezone
  ansible.builtin.include_tasks:
    file: tasks/time_zone.yml

- name: Install packages
  ansible.builtin.include_tasks:
    file: tasks/packages.yml

- name: Configure SSH keys
  ansible.builtin.include_tasks:
    file: tasks/ssh_keys.yml

- name: Disable root account for security
  ansible.builtin.include_tasks:
    file: tasks/root.yml
