---
- name: Configure servers
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Run tasks in servers role
      ansible.builtin.import_role:
        name: servers
        tasks_from: main.yml
