- name: Install updates
  hosts: servers
  become: true
  gather_facts: false

  tasks:
    - name: Upgrade all packages
      ansible.builtin.include_tasks:
        file: roles/servers/tasks/yum_upgrade.yml
