---
- name: Upgrade all packages on servers
  hosts: servers
  become: true
  gather_facts: false

  tasks:
    - name: Include package upgrade tasks
      ansible.builtin.include_tasks:
        file: ad_hoc_tasks/yum_upgrade.yml
