---
- name: Ensure essential packages are installed
  ansible.builtin.package:
    name:
      - git
      - vim
      - tmux
      - python3
    state: present
  
  ansible.builtin.package:
    name:
      - podman
      - podman-compose
      - podman-docker
    state: absent
