---
- name: Ensure essential packages are installed
  ansible.builtin.package:
    name:
      - git
      - vim
      - tmux
      - podman
      - podman-compose
      - python3
    state: present
  register: packages_installed

- name: Show packages that were installed
  ansible.builtin.debug:
    msg: "{{ packages_installed.results }}"
