---
- name: Ensure all packages are up to date
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
  register: updated_packages
  until: updated_packages is success
  retries: 2
  delay: 10

- name: Show updated packages
  ansible.builtin.debug:
    msg: "{{ updated_packages.results }}"

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
    state: absent
