---
- name: Ensure all packages are up to date
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
    state: absent
