---
- name: Ensure systemd service for Dockge exists
  ansible.builtin.copy:
    dest: /etc/systemd/system/dockge.service
    mode: '0644'
    owner: root
    group: root
    content: |
      [Unit]
      Description=Dockge
      After=network.target
      Requires=network.target

      [Service]
      Type=simple
      WorkingDirectory=/opt/dockge
      ExecStart=/usr/bin/docker-compose up
      ExecStop=/usr/bin/docker-compose down
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply Dockge service changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure Dockge systemd service is enabled and started
  ansible.builtin.systemd:
    name: dockge
    enabled: true
    state: started
