---
- name: Install common packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Disable root account
  ansible.builtin.include_tasks:
    file: root.yml

- name: Set timezone
  ansible.builtin.include_tasks:
    file: time_zone.yml
