---
- name: Packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Prometheus Node Exporter
  ansible.builtin.include_tasks:
    file: prometheus_node_exporter.yml

- name: Root
  ansible.builtin.include_tasks:
    file: root.yml

- name: SSH
  ansible.builtin.include_tasks:
    file: ssh_keys.yml

- name: Timezone
  ansible.builtin.include_tasks:
    file: time_zone.yml
