---
- name: Set system timezone
  ansible.builtin.include_tasks:
    file: time_zone.yml

- name: Install packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Configure SSH keys
  ansible.builtin.include_tasks:
    file: ssh_keys.yml

- name: Disable root account for security
  ansible.builtin.include_tasks:
    file: root.yml
