- name: Git should be installed and up to date
  ansible.builtin.package:
    name:
      - git

- name: Vim should be installed and up to date
  ansible.builtin.package:
    name:
      - vim

- name: Tmux should be installed and up to date
  ansible.builtin.package:
    name:
      - tmux
