---
- name: Ensure essential packages are installed
  ansible.builtin.package:
    name: "{{ essential_packages }}"
    state: present
  vars:
    essential_packages:
      - git
      - nu
      - python3
      - tmux
      - vim
