- name: Git should be installed
  ansible.builtin.package:
    name:
      - git

- name: Vim should be installed
  ansible.builtin.package:
    name:
      - vim

- name: Tmux should be installed
  ansible.builtin.package:
    name:
      - tmux
