---
- name: Systemd service for dockge should exist
  ansible.builtin.copy:
    dest: /etc/systemd/system/dockge.service
    mode: '0644'
    copy: |
      [Unit]
      Description=Dockge
      After=network.target
      Requires=network.target
      [Service]
      Type=simple
      WorkingDirectory=/root/dockge
      ExecStart=/bin/podman-compose up -d
      ExecStop=/bin/podman-compose down
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

- name: Systemd service Semaphore should exist
  ansible.builtin.copy:
    dest: /etc/systemd/system/semaphore.service
    mode: '0644'
    copy: |
      [Unit]
      Description=Semaphore
      After=network.target
      Requires=network.target
      [Service]
      Type=simple
      WorkingDirectory=/opt/stacks/semaphore
      ExecStart=/bin/podman-compose up -d
      ExecStop=/bin/podman-compose down
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

- name: Systemd service for Home Assistant should exist
  ansible.builtin.copy:
    dest: /etc/systemd/system/homeassistant.service
    mode: '0644'
    copy: |
      [Unit]
      Description=Home Assistant
      After=network.target
      Requires=network.target
      [Service]
      Type=simple
      WorkingDirectory=/opt/stacks/homeassistant
      ExecStart=/bin/podman-compose up -d
      ExecStop=/bin/podman-compose down
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

- name: Systemd service for Qbittorrent should exist
  ansible.builtin.copy:
    dest: /etc/systemd/system/qbittorrent.service
    mode: '0644'
    copy: |
      [Unit]
      Description=qBittorrent
      After=network.target
      Requires=network.target
      [Service]
      Type=simple
      WorkingDirectory=/opt/stacks/qbittorrent
      ExecStart=/bin/podman-compose up -d
      ExecStop=/bin/podman-compose down
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

- name: Systemd service for Cloudflared should exist
  ansible.builtin.copy:
    dest: /etc/systemd/system/cloudflared.service
    mode: '0644'
    copy: |
      [Unit]
      Description=Cloudflared
      After=network.target
      Requires=network.target
      [Service]
      Type=simple
      WorkingDirectory=/opt/stacks/cloudflared
      ExecStart=/bin/podman-compose up -d
      ExecStop=/bin/podman-compose down
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

- name: Systemd service dockge should be enabled and started
  ansible.builtin.systemd:
    name: dockge
    enabled: true
    state: started
    daemon_reload: true

- name: Systemd service semaphore should be enabled and started
  ansible.builtin.systemd:
    name: semaphore
    enabled: true
    state: started
    daemon_reload: true

- name: Systemd service homeassistant should be enabled and started
  ansible.builtin.systemd:
    name: homeassistant
    enabled: true
    state: started
    daemon_reload: true

- name: Systemd service qbittorrent should be enabled and started
  ansible.builtin.systemd:
    name: qbittorrent
    enabled: true
    state: started
    daemon_reload: true

- name: Systemd service cloudflared should be enabled and started
  ansible.builtin.systemd:
    name: cloudflared
    enabled: true
    state: started  
    daemon_reload: true
