---
- name: Ensure EPEL is installed
  ansible.builtin.yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux
    baseurl: "https://dl.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/Everything/x86_64/"
    gpgcheck: true
    enabled: true
