---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container: alpine/ansible
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Lint code.
        run: ansible-lint
