---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          targets: "."
          args: "-c .ansible-lint"
